//
//  VLDLogging.h
//  ValidicCore
//
//  Created by Phil Cole on 9/25/19.
//  Copyright © 2019 Validic. All rights reserved.
//

#import <Foundation/Foundation.h>

// Mask for the functional Validic frameworks where debug messages are desired
typedef NS_OPTIONS(NSUInteger, VLDLogMask) {
    VLDLogBluetooth = 1 << 0,
    VLDLogHealthKit = 1 << 1,
    VLDLogOCR       = 1 << 2,
    VLDLogCore      = 1 << 3
};

/** Custom log handler block
 @param sdkTag the name of the specific Validic SDK that generated the log.
 @param message the log message generated by the Validic SDK.
 */
typedef void(^VLDLogHandler) (NSString *sdkTag, NSString *message);

@interface VLDLogging : NSObject

/** Enables or disbales logging
 */
@property(nonatomic) BOOL isEnabled;

/**
 Mask to output debug messages from Validic Frameworks. Ex: [[VLDLogging sharedInstance] setLog:VLDLogBluetooth & VLDLogCore];
 */
@property(nonatomic) NSUInteger log;

/** Custom log handler. If set to nil, logging is processed by the Validic SDK via logging to console
 */
- (void)setLogger:(VLDLogHandler)handler;
-(VLDLogHandler)getLogger;

/** sharedInstance returns the VLDLogging singleton and should be the only way VLDLogging is accessed. */
+ (instancetype)sharedInstance;

@end

